#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python manage.py collectstatic --no-input

if [ "$DJANGO_DEBUG" -eq  "1" ]
then
    python manage.py runserver_plus 0.0.0.0:8000
else
    gunicorn --bind :$1 TheHaloMod.wsgi:application
fi
